name: meetups

services:
  django:
    container_name: meetups_django
    entrypoint: /app/entrypoint.sh
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - celery
    networks:
      - app_network
    restart: unless-stopped

  celery:
    container_name: meetups_celery
    build: .
    command: celery -A matcher.tasks worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - app_network
    restart: unless-stopped

  rabbitmq:
    container_name: meetups_rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"  # RabbitMQ management console
      - "5672:5672"    # RabbitMQ default port
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge